version: '3.1'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '5555:80'
        env_file:
            - .env
        volumes:
            - ./app:/var/www/html

    db:
        image: 'mariadb:10.6.4'
        restart: always
        environment:
            - .env
        env_file:
            - .env
        volumes:
            # Pour lancer un dump automatiquement au montage du conteneur
            - ./database/mt4-data.sql:/docker-entrypoint-initdb.d/mt4-data.sql


    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - '8080:80'
        environment:
            - PMA_ARBITRARY=1